version: "2.1"
services:
  #######################################
  # Web App
  #######################################
  app:
    image: "ncarlier/keeper-web-app:latest"
    env_file: "etc/default/${ENV:-dev}.env"
    command: "${CMD:-start}"
    volumes:
      - ${PWD}:${APP_SRC_DIR:-/usr/src/app_src}
    ports:
      - "${PORT:-3000}:3000"
